"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.us_statesRoutes = void 0;
const express_1 = require("express");
const authorization_1 = require("../middleware/authorization");
const states_controller_1 = require("../controllers/states_controller");
exports.us_statesRoutes = (0, express_1.Router)();
exports.us_statesRoutes.get('/us_states', states_controller_1.getus_states);
exports.us_statesRoutes.get('/us_states/:id', authorization_1.authenticateToken, states_controller_1.getus_statesById);
exports.us_statesRoutes.post('/createState', authorization_1.authenticateToken, states_controller_1.createState);
exports.us_statesRoutes.delete('/deleteState/:id', authorization_1.authenticateToken, states_controller_1.deleteStates);
exports.us_statesRoutes.put('/updateStates/:id', authorization_1.authenticateToken, states_controller_1.updateStates);
