"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.usuariosRoutes = void 0;
const express_1 = require("express");
const usuarios_controller_1 = require("../controllers/usuarios_controller");
exports.usuariosRoutes = (0, express_1.Router)();
exports.usuariosRoutes.get('/users', usuarios_controller_1.getusers);
exports.usuariosRoutes.get('/users/:id', usuarios_controller_1.getusersById);
exports.usuariosRoutes.post('/createusers', usuarios_controller_1.createusers);
exports.usuariosRoutes.delete('/deleteusers/:id', usuarios_controller_1.deleteusers);
exports.usuariosRoutes.put('/updateusers/:id', usuarios_controller_1.updateusers);
